on: 
  push:
  release:
  pull_request:
    branches:
    - main

name: Publish Binary
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
      - name: Run Build
        run: make build
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@main
      #   with:
      #     name: insights-cache-projects-test
      #     path: ./bin
      - uses: actions/upload-artifact@main
        if: $GITHUB_EVENT_NAME == 'push'
        with:
          name: insights-cache-projects-test
          path: ./bin